from fastapi.testclient import TestClient

from sentinelgraph.app import app
from sentinelgraph.factory import build_engines
from sentinelgraph.models import MemorySyncRequest, ScannerChaosRequest
from sentinelgraph.security_audit import normalize_provider_finding
from sentinelgraph.storage import Store


def test_scanner_validation_can_plan_branch_cleanup(tmp_path):
    engines = build_engines(Store(tmp_path / "cleanup.db"))

    result = engines.scanner_chaos.run(
        ScannerChaosRequest(repo="payments-platform", cleanup_branch=True)
    )

    assert any(action["action"] == "delete_branch" for action in result["actions"])


def test_memory_sync_can_target_repo_and_wiki(tmp_path):
    engines = build_engines(Store(tmp_path / "memory-sync.db"))

    result = engines.memory_suite.sync(
        MemorySyncRequest(repo="payments-platform", external_target="both")
    )

    actions = {action["action"] for action in result["actions"]}
    assert "commit_files" in actions
    assert "sync_wiki_pages" in actions


def test_advisory_route_and_slash_command_route():
    client = TestClient(app)

    advisory = client.post("/advisories/enrich", json={})
    assert advisory.status_code == 200
    assert advisory.json()["count"] == 0

    slash = client.post(
        "/commands/slash",
        json={"repo": "payments-platform", "command": "/sentinelgraph scanner"},
    )
    assert slash.status_code == 200
    assert slash.json()["status"] == "executed"
    assert slash.json()["result"]["files"]

    exploit = client.post(
        "/exploitability/simulate",
        json={
            "repo": "payments-platform",
            "title": "Auth bypass in gateway middleware",
            "category": "auth",
            "severity": "high",
            "file": "services/gateway/auth.py",
        },
    )
    assert exploit.status_code == 200
    assert exploit.json()["score"] >= 30
    assert exploit.json()["attack_chain"]

    ai = client.post(
        "/ai-governance/analyze",
        json={
            "repo": "payments-platform",
            "mr_id": "ai-1",
            "title": "AI generated auth update",
            "author": "dev",
            "files_changed": ["services/gateway/auth.py"],
            "diff_summary": "Generated by assistant; removed validation; jwt.decode no verify",
            "ai_assisted": True,
        },
    )
    assert ai.status_code == 200
    assert ai.json()["risk_score"] >= 40
    assert ai.json()["required_controls"]

    debate = client.post(
        "/security/debate",
        json={"repo": "payments-platform", "subject_id": "ai-1", "prompt": "Should this merge?"},
    )
    assert debate.status_code == 200
    assert debate.json()["perspectives"]
    assert debate.json()["verdict"] in {"block-until-evidence", "require-extra-review", "approve-with-monitoring"}


def test_provider_finding_normalization_extracts_advisory_ids():
    finding = normalize_provider_finding(
        {
            "title": "Known vulnerable dependency",
            "severity": "high",
            "identifiers": [
                {"type": "cwe", "value": "CWE-79"},
                {"type": "cve", "value": "CVE-2024-12345"},
                {"type": "ghsa", "value": "GHSA-abcd-efgh-ijkl"},
            ],
        }
    )

    assert finding["cwe"] == "CWE-79"
    assert finding["cve"] == "CVE-2024-12345"
    assert finding["ghsa"] == "GHSA-abcd-efgh-ijkl"
