"""AI coding governance and multi-perspective security debate."""

from __future__ import annotations

from typing import Dict, List

from .graph import SecurityGraph
from .models import MergeRequestInput, SecurityDebateRequest
from .utils import clamp, stable_id


class AICodeGovernanceEngine:
    def __init__(self, graph: SecurityGraph):
        self.graph = graph

    def analyze(self, mr: MergeRequestInput) -> Dict[str, object]:
        signals = ai_risk_signals(mr)
        score = clamp(sum(signal["weight"] for signal in signals))
        if not mr.ai_assisted and not any(signal["code"] == "generated-code-signal" for signal in signals):
            score = round(score * 0.65, 2)
        level = "low"
        if score >= 75:
            level = "critical"
        elif score >= 50:
            level = "high"
        elif score >= 25:
            level = "medium"
        model = model_fingerprint(mr)
        result = {
            "repo": mr.repo,
            "mr_id": mr.mr_id,
            "model_fingerprint": model,
            "risk_score": score,
            "level": level,
            "signals": signals,
            "required_controls": required_ai_controls(signals),
            "model_profile": self._model_profile(model),
        }
        self.graph.store.insert_analysis(
            stable_id("ai-governance", mr.repo, mr.mr_id),
            mr.repo,
            mr.mr_id,
            "ai-governance",
            score,
            level,
            result,
        )
        return result

    def _model_profile(self, model: str) -> Dict[str, object]:
        analyses = [a for a in self.graph.store.list_analyses() if a["subject_type"] == "ai-governance"]
        related = [a for a in analyses if a["payload"].get("model_fingerprint") == model]
        mean = sum(a["score"] for a in related) / max(len(related), 1)
        common = {}
        for analysis in related:
            for signal in analysis["payload"].get("signals", []):
                common[signal["code"]] = common.get(signal["code"], 0) + 1
        return {
            "samples": len(related),
            "mean_risk": round(mean, 2),
            "common_signals": sorted(common.items(), key=lambda item: item[1], reverse=True)[:8],
        }


class SecurityDebateEngine:
    def __init__(self, graph: SecurityGraph):
        self.graph = graph

    def debate(self, request: SecurityDebateRequest) -> Dict[str, object]:
        subject = self._subject(request)
        perspectives = [
            attacker_perspective(subject, request.context),
            defender_perspective(subject, request.context),
            compliance_perspective(subject, request.context),
            runtime_perspective(self.graph, request),
            exploitability_perspective(subject, request.context),
        ]
        high_votes = sum(1 for item in perspectives if item["risk"] in {"high", "critical"})
        blockers = [item for item in perspectives if item.get("blocker")]
        verdict = "approve-with-monitoring"
        if blockers or high_votes >= 2:
            verdict = "block-until-evidence"
        elif high_votes == 1:
            verdict = "require-extra-review"
        return {
            "repo": request.repo,
            "subject": subject,
            "prompt": request.prompt,
            "perspectives": perspectives,
            "verdict": verdict,
            "required_evidence": sorted({evidence for item in perspectives for evidence in item.get("required_evidence", [])}),
        }

    def _subject(self, request: SecurityDebateRequest) -> Dict[str, object]:
        if request.subject_id:
            for analysis in self.graph.store.list_analyses(request.repo):
                if analysis["subject_id"] == request.subject_id:
                    return analysis["payload"]
            for finding in self.graph.store.list_findings(request.repo):
                if finding["id"] == request.subject_id:
                    return finding
        return request.context or {"subject_type": request.subject_type, "subject_id": request.subject_id}


def ai_risk_signals(mr: MergeRequestInput) -> List[Dict[str, object]]:
    text = f"{mr.title} {mr.description} {mr.diff_summary} {' '.join(mr.files_changed)}".lower()
    signals: List[Dict[str, object]] = []
    if mr.ai_assisted or any(term in text for term in ["generated by", "copilot", "cursor", "llm", "ai-generated"]):
        signals.append({"code": "generated-code-signal", "weight": 12, "message": "Change appears AI-assisted or generated."})
    if any(term in text for term in ["jwt.decode(", "verify=false", "options={'verify_signature': false}", "no verify"]):
        signals.append({"code": "generated-auth-risk", "weight": 24, "message": "Auth/token logic may be missing verification."})
    if any(term in text for term in ["md5", "sha1", "random.random", "ecb"]):
        signals.append({"code": "unsafe-crypto", "weight": 20, "message": "Unsafe cryptography pattern appears in generated context."})
    if any(term in text for term in ["eval(", "exec(", "subprocess", "os.system"]):
        signals.append({"code": "code-execution", "weight": 22, "message": "Dynamic execution or shell execution needs strict review."})
    if any(term in text for term in ["remove validation", "removed validation", "skip validation", "bypass", "- validate", "- require"]):
        signals.append({"code": "dropped-validation", "weight": 25, "message": "Change appears to remove or bypass validation."})
    if dependency_change_without_lock(mr):
        signals.append({"code": "dependency-hallucination", "weight": 16, "message": "Dependency manifest changed without lock/provenance evidence."})
    if any(term in text for term in ["todo security", "temporary allow", "disable check", "catch exception"]):
        signals.append({"code": "prompt-induced-backdoor", "weight": 18, "message": "Temporary bypass/backdoor language appears in code context."})
    if not any(path.startswith("tests/") or "/test" in path for path in mr.files_changed) and signals:
        signals.append({"code": "missing-negative-tests", "weight": 12, "message": "AI-risky change lacks test file changes."})
    return signals


def model_fingerprint(mr: MergeRequestInput) -> str:
    ai = mr.metadata.get("ai") if isinstance(mr.metadata, dict) else {}
    if isinstance(ai, dict):
        return str(ai.get("model") or ai.get("model_family") or ai.get("tool") or "unknown-ai")
    return "unknown-ai" if mr.ai_assisted else "human-or-unknown"


def dependency_change_without_lock(mr: MergeRequestInput) -> bool:
    manifests = {"package.json", "pyproject.toml", "requirements.txt", "go.mod", "Cargo.toml", "Gemfile"}
    locks = {"package-lock.json", "pnpm-lock.yaml", "yarn.lock", "poetry.lock", "go.sum", "Cargo.lock", "Gemfile.lock"}
    names = {path.rsplit("/", 1)[-1] for path in mr.files_changed}
    return bool(names & manifests) and not bool(names & locks)


def required_ai_controls(signals: List[Dict[str, object]]) -> List[str]:
    controls = set()
    for signal in signals:
        code = signal["code"]
        if code in {"generated-auth-risk", "dropped-validation"}:
            controls.add("auth-boundary negative tests")
            controls.add("security reviewer approval")
        if code in {"unsafe-crypto", "code-execution"}:
            controls.add("manual code owner review")
            controls.add("SAST evidence")
        if code == "dependency-hallucination":
            controls.add("dependency provenance and lockfile verification")
        if code == "missing-negative-tests":
            controls.add("negative regression tests")
    return sorted(controls)


def attacker_perspective(subject: Dict[str, object], context: Dict[str, object]) -> Dict[str, object]:
    text = f"{subject} {context}".lower()
    risk = "critical" if any(term in text for term in ["auth bypass", "rce", "secret"]) else "high" if any(term in text for term in ["auth", "sql", "ssrf"]) else "medium"
    return {"role": "attacker", "risk": risk, "argument": "Can this be reached, chained, or abused for privilege/data impact?", "required_evidence": ["attack-path test"]}


def defender_perspective(subject: Dict[str, object], context: Dict[str, object]) -> Dict[str, object]:
    text = f"{subject} {context}".lower()
    blocker = "missing-negative-tests" in text or "dropped-validation" in text
    return {"role": "defender", "risk": "high" if blocker else "medium", "blocker": blocker, "argument": "Require proof that guardrails and tests cover the changed path.", "required_evidence": ["negative tests", "scanner evidence"]}


def compliance_perspective(subject: Dict[str, object], context: Dict[str, object]) -> Dict[str, object]:
    text = f"{subject} {context}".lower()
    risk = "high" if any(term in text for term in ["pci", "hipaa", "encryption", "secret", "customer"]) else "medium"
    return {"role": "compliance", "risk": risk, "argument": "Map the change to audit evidence and approval lineage.", "required_evidence": ["approval lineage", "control mapping"]}


def runtime_perspective(graph: SecurityGraph, request: SecurityDebateRequest) -> Dict[str, object]:
    events = graph.store.list_runtime_events(request.repo)
    risk = "high" if events else "low"
    return {"role": "runtime", "risk": risk, "argument": f"{len(events)} runtime signals are available for correlation.", "required_evidence": ["runtime correlation"] if events else []}


def exploitability_perspective(subject: Dict[str, object], context: Dict[str, object]) -> Dict[str, object]:
    text = f"{subject} {context}".lower()
    route = any(term in text for term in ["gateway", "api", "route", "controller", "handler"])
    return {"role": "exploitability", "risk": "high" if route else "medium", "argument": "Prioritize reachable code paths and known mitigations.", "required_evidence": ["reachability analysis"]}
